version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - careerconnect-network
    environment:
      # KRaft
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8090:8080
    networks:
      - careerconnect-network
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERs_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERs_0_KSQLDBSERVER: http://ksqldb0:8080

  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      - POSTGRES_DB=notificationDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - careerconnect-network
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  notification-service:
    image: gaganhere/career-connect/notification-service
    container_name: notification-service
    networks:
      - careerconnect-network
    depends_on:
      - discovery-server
      - notification-db
      - kafka

  discovery-server:
    image: gaganhere/career-connect/discovery-server
    container_name: discovery-server
    networks:
      - careerconnect-network
    ports:
      - "8761:8761"

networks:
  careerconnect-network:

volumes:
  kafka_data:
  notification-db-data:
