apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connections-db
  serviceName: connections-db
  template:
    metadata:
      labels:
        app: connections-db
    spec:
      containers:
        - name: connections-db
          image: neo4j
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
            env:
              - name: NEO4J_AUTH
                value: neo4j/password
          ports:
            - containerPort: 7687
              name: bolt
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "standard-rwo"
        volumeMode: Filesystem

---

apiVersion: v1
kind: Service
metadata:
  name: connections-db
spec:
  clusterIp: None
  selector:
    app: connections-db
  ports:
    - port: 7687
      targetPort: 7687
