apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  serviceName: "neo4j"
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:4.4.39-community
          resources:
            limits:
              cpu: "200m"
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 600Mi
          ports:
            - containerPort: 7687 # Bolt
          env:
            - name: NEO4J_AUTH
              value: "neo4j/password" # Change as per your setup
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "512M"
