apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service
spec:
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
        - name: posts-service
          image: gaganhere/career-connect/posts-service
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
