apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: posts-db
spec:
  selector:
    matchLabels:
      app: posts-db
  serviceName: posts-db
  replicas: 1
  template:
    metadata:
      labels:
        app: posts-db
